sudo: false
language: python
python:
  # support debian 9, 10, 11
  - "3.7"
  - "3.9"
  - "3.11"
cache:
  pip: true
install:
  - docker compose up
  - pip install -Ur tests/requirements.txt
script:
  - cd tests && pytest
